services:
  pbs-exporter:
    build: .
    # image: ghcr.io/natrontech/pbs-exporter:latest
    container_name: pbs-exporter
    user: '65534'
    restart: always
    ports:
      - "10019:10019"
    environment:
      - PBS_ENDPOINT=https://pbs-server:8007
      - PBS_INSECURE=false
      - PBS_USERNAME_FILE=/run/secrets/proxmoxbackup-username
      - PBS_API_TOKEN_NAME_FILE=/run/secrets/proxmoxbackup-api-token-name
      - PBS_API_TOKEN_FILE=/run/secrets/proxmoxbackup-api-token
    secrets:
    - proxmoxbackup-username
    - proxmoxbackup-api-token-name
    - proxmoxbackup-api-token

secrets:
  # example with secret files in .secrets folder
  proxmoxbackup-username:
    file: "./.secrets/proxmoxbackup_username.secret"
  proxmoxbackup-api-token-name:
    file: "./.secrets/proxmoxbackup_api_token_name.secret"
  proxmoxbackup-api-token:
    file: "./.secrets/proxmoxbackup_api_token.secret"
